### ISSUE TITLE
Create plot_belief_bits_correct()

### ISSUE THREAD

**Issue by elplatt** [bodon2018/REMs#6]
This should be similar to plot_beliefs_correct() but should plot one line for each bit. So if the first bit's true value is 0, the y value of one of the lines should be the fraction of nodes that have 0 for that bit.

**Comment by bodon2018** [comment]
I created a helper function to get the fraction of nodes that have the same true value in a given bit. I named it "fraction_correct_bit". I couldn't use the original "get_belief_bit_fraction" because it didn't take a true value, and it didn't check for equality either. I put it right above  "plot_belief_bits_correct()" so it is easy to see if you take a look at it, but eventually it should be in another section, so all the plots are together.
